### ISSUE TITLE
Is it possible to use it also in MAC OS terminal?

### ISSUE THREAD

**Issue by kjw1801** [demirhanaydin/node-mi-flora#7]
nice to meet you.
Is it possible to use it also in MAC OS terminal?
I was trying to communicate with Bluetooth on the MAC pro
I can not connect the device.

Do I need to set the Bluetooth setting on the node separately?

**Comment by demirhanaydin** [comment]
It's possible. I've developed it on my macbook. But make sure your mac has bluetooth 4.0 support. Also one of the users reported that mi flora's default name has changed. If you updated your firmware, maybe it's better to change the name of the device or try to use mac address. Checkout https://github.com/demirhanaydin/node-mi-flora/issues/5
